# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose.yml up -d
version: '3.8'
# docker-compose -f environment-docker-compose.yml up -d
services:
  chatgpt-data-app:
    image: fuzhengwei/chatgpt-data-app:1.1
    container_name: chatgpt-data-app
    ports:
      - "8091:8091"
    environment:
      - TZ=PRC
      - SERVER_PORT=8091
      - APP_CONFIG_API_VERSION=v1
      - APP_CONFIG_CROSS_ORIGIN=*
      - THREAD_POOL_EXECUTOR_CONFIG_CORE_POOL_SIZE=20
      - THREAD_POOL_EXECUTOR_CONFIG_MAX_POOL_SIZE=50
      - THREAD_POOL_EXECUTOR_CONFIG_KEEP_ALIVE_TIME=5000
      - THREAD_POOL_EXECUTOR_CONFIG_BLOCK_QUEUE_SIZE=5000
      - THREAD_POOL_EXECUTOR_CONFIG_POLICY=CallerRunsPolicy
      - CHATGPT_SDK_CONFIG_API_HOST=https://sdk.xfg.im/
      - CHATGPT_SDK_CONFIG_API_KEY=sk-7f6qDrzz0xBhN5leKTM2T3BlbkFJlY****
      - WX_CONFIG_ORIGINALID=gh_c5ce6e4a0e0e
      - WX_CONFIG_APPID=wxad979c0307864a66
      - WX_CONFIG_TOKEN=b8b6
    volumes:
      - ./log:/var/log/x-api-app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
